"""add performance indexes

Revision ID: 40c88d4e4407
Revises: 
Create Date: 2026-04-20 20:25:31.731633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c88d4e4407'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation_risk', schema=None) as batch_op:
        batch_op.create_index('ix_participation_risk_predicted_at', ['predicted_at'], unique=False)
        batch_op.create_index('ix_participation_risk_risk_level', ['risk_level'], unique=False)

    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.create_index('ix_reward_redemptions_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_reward_redemptions_user_created_at', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_role_created_at', ['role', 'created_at'], unique=False)
        batch_op.create_index('ix_users_role_name', ['role', 'name'], unique=False)
        batch_op.create_index('ix_users_role_total_points', ['role', 'total_points'], unique=False)

    with op.batch_alter_table('waste_deposits', schema=None) as batch_op:
        batch_op.create_index('ix_waste_deposits_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_waste_deposits_status_waste_created', ['status', 'waste_type', 'created_at'], unique=False)
        batch_op.create_index('ix_waste_deposits_user_created_at', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_deposits', schema=None) as batch_op:
        batch_op.drop_index('ix_waste_deposits_user_created_at')
        batch_op.drop_index('ix_waste_deposits_status_waste_created')
        batch_op.drop_index('ix_waste_deposits_status_created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_total_points')
        batch_op.drop_index('ix_users_role_name')
        batch_op.drop_index('ix_users_role_created_at')

    with op.batch_alter_table('reward_redemptions', schema=None) as batch_op:
        batch_op.drop_index('ix_reward_redemptions_user_created_at')
        batch_op.drop_index('ix_reward_redemptions_status_created_at')

    with op.batch_alter_table('participation_risk', schema=None) as batch_op:
        batch_op.drop_index('ix_participation_risk_risk_level')
        batch_op.drop_index('ix_participation_risk_predicted_at')

    # ### end Alembic commands ###
