"""add rejection_reason to waste_deposits

Revision ID: 45201554263a
Revises: c4e3f2a1b9d8
Create Date: 2026-07-15 18:16:25.156790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45201554263a'
down_revision = 'c4e3f2a1b9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_waste_type_code'))

    with op.batch_alter_table('waste_deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_deposits', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missions_waste_type_code'), ['waste_type_code'], unique=False)

    # ### end Alembic commands ###
