"""add_deadline_to_missions

Revision ID: ad000d27bcfa
Revises: 3f5925f141e9
Create Date: 2026-07-15 18:31:01.535788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad000d27bcfa'
down_revision = '3f5925f141e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
